spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8081